import { defineConfig } from "drizzle-kit"

const url = process.env.DATABASE_URL
if (!url) {
  throw new Error(
    "DATABASE_URL is not set. Copy .env.example to .env and fill it in."
  )
}

export default defineConfig({
  // Better Auth's CLI owns ./src/db/schema.ts (regenerated by auth:generate).
  // Tenant tables live in their own file so the auth schema can be safely
  // overwritten by the CLI without losing our hand-written definitions.
  // History tables live in the `history` Postgres schema (Timescale hypertables).
  schema: [
    "./src/db/schema.ts",
    "./src/db/tenant-schema.ts",
    "./src/db/history-schema.ts",
  ],
  out: "./drizzle",
  dialect: "postgresql",
  dbCredentials: { url },
  // Strict mode prints warnings instead of silently destructive changes
  // when running drizzle-kit push.
  strict: true,
  verbose: true,
})
